// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySinhVien_BTL.Data;

#nullable disable

namespace QuanLySinhVien_BTL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251028065919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySinhVien_BTL.Models.Department", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfEstablishment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentCode");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentCode = "KCNTT",
                            DateOfEstablishment = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Công nghệ thông tin"
                        },
                        new
                        {
                            DepartmentCode = "KKT",
                            DateOfEstablishment = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kinh tế"
                        },
                        new
                        {
                            DepartmentCode = "KNN",
                            DateOfEstablishment = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ngoại ngữ"
                        },
                        new
                        {
                            DepartmentCode = "KKHMT",
                            DateOfEstablishment = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Khoa học máy tính"
                        });
                });

            modelBuilder.Entity("QuanLySinhVien_BTL.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("QuanLySinhVien_BTL.Models.Major", b =>
                {
                    b.Property<string>("MajorCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("int");

                    b.HasKey("MajorCode");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            MajorCode = "CNTT",
                            Detail = "Phần mềm, mạng",
                            Name = "Công nghệ thông tin",
                            TotalCredits = 120
                        },
                        new
                        {
                            MajorCode = "KT",
                            Detail = "Tài chính, quản trị",
                            Name = "Kinh tế",
                            TotalCredits = 130
                        },
                        new
                        {
                            MajorCode = "KHMT",
                            Detail = "Thuật toán",
                            Name = "Khoa học máy tính",
                            TotalCredits = 125
                        },
                        new
                        {
                            MajorCode = "NNA",
                            Detail = "Tiếng Anh và văn hóa",
                            Name = "Ngôn ngữ Anh",
                            TotalCredits = 115
                        });
                });

            modelBuilder.Entity("QuanLySinhVien_BTL.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("MajorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MajorCode");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("QuanLySinhVien_BTL.Models.Lecturer", b =>
                {
                    b.HasOne("QuanLySinhVien_BTL.Models.Department", "Department")
                        .WithMany("Lecturers")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("QuanLySinhVien_BTL.Models.Student", b =>
                {
                    b.HasOne("QuanLySinhVien_BTL.Models.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("QuanLySinhVien_BTL.Models.Department", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("QuanLySinhVien_BTL.Models.Major", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
